apiVersion: v1
kind: Service
metadata:
  name: micro-tools-service
spec:
  selector:
    app: micro-tools
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort
